#@ load("@ytt:data", "data")

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-logging-triggers
  namespace: #@ data.values.namespace
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-triggers
data:
  zap-logger-config: |
    {
      "level": "info",
      "development": false,
      "sampling": {
        "initial": 100,
        "thereafter": 100
      },
      "outputPaths": ["stdout"],
      "errorOutputPaths": ["stderr"],
      "encoding": "json",
      "encoderConfig": {
        "timeKey": "ts",
        "levelKey": "level",
        "nameKey": "logger",
        "callerKey": "caller",
        "messageKey": "msg",
        "stacktraceKey": "stacktrace",
        "lineEnding": "",
        "levelEncoder": "",
        "timeEncoder": "iso8601",
        "durationEncoder": "",
        "callerEncoder": ""
      }
    }
  #! To configure logging levels, this key must match the string argument
  #! used in the main.go file to the InterceptorMainWithConfig function
  #! loglevel.<arg>
  loglevel.interceptors: "info"
