#@ load("@ytt:data", "data")

apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ data.values.name
  namespace: #@ data.values.namespace
  labels:
    app.kubernetes.io/name: #@ data.values.name
    app.kubernetes.io/component: interceptors
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: "devel"
    app.kubernetes.io/part-of: tekton-triggers
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: #@ data.values.name
      app.kubernetes.io/component: interceptors
      app.kubernetes.io/instance: default
      app.kubernetes.io/part-of: tekton-triggers
  template:
    metadata:
      labels:
        app.kubernetes.io/name: #@ data.values.name
        app.kubernetes.io/component: interceptors
        app.kubernetes.io/instance: default
        app.kubernetes.io/version: "devel"
        app.kubernetes.io/part-of: tekton-triggers
        app: #@ data.values.name
        triggers.tekton.dev/release: "devel"
        version: "devel"
    spec:
      serviceAccountName: tekton-triggers-custom-interceptor
      containers:
      - name: #@ data.values.name
        image: #@ "ko://" + data.values.package + "/cmd/interceptor"
        args: [
          "-logtostderr",
          "-stderrthreshold", "INFO",
        ]
        env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_LOGGING_NAME
          value: config-logging-triggers
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /live
            port: 8082
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 65532
          runAsGroup: 65532
          capabilities:
            drop:
            - all
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: #@ data.values.name
    app.kubernetes.io/component: interceptors
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: "devel"
    app.kubernetes.io/part-of: tekton-triggers
    triggers.tekton.dev/release: "devel"
    app: #@ data.values.name
    version: "devel"
  name: #@ data.values.name
  namespace: #@ data.values.namespace
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 8082
  selector:
    app.kubernetes.io/name: #@ data.values.name
    app.kubernetes.io/component: interceptors
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-triggers
