#@ load("@ytt:data", "data")

apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers-custom-interceptor
  namespace: #@ data.values.namespace
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-triggers
