#@ load("@ytt:data", "data")

apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers-custom-interceptor
  namespace: #@ data.values.namespace
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-triggers
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-triggers-custom-interceptor
  namespace: #@ data.values.namespace
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-triggers
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-triggers-custom-interceptors
  namespace: #@ data.values.namespace
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-triggers
subjects:
  - kind: ServiceAccount
    name: tekton-triggers-custom-interceptor
    namespace: #@ data.values.namespace
roleRef:
  kind: Role
  name: tekton-triggers-custom-interceptor
  apiGroup: rbac.authorization.k8s.io
